name: Push to Development Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pushing into other repo
        run: |
          echo "${{ github.token  }}" | gh auth login --with-token
          
          
          echo $(ls)
          
          # cloning deployment repo
          git clone https://${{ secrets.gh_token }}@github.com/p3h3/DaronBMS-Interface-Web.git
          
          
          echo $(ls)
          
          #moving everything from the existing repo into the deployment repo
          ls | grep -v DaronBMS-Interface-Web | xargs mv -t DaronBMS-Interface-Web
          
          
          echo $(ls)
          
          #committing and pushing into other repo
          cd DaronBMS-Interface-Web
          echo $(ls)
          
          git config user.email "hi@p3h3.de"
          git config user.name "p3h3"
          
          git add .
          git commit -m "automatic update from main branch of DragonBMS-Interface-Web"
          git push
          
