name: Push to Development Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Downloading releases
        run: |
          echo "${{ github.token  }}" | gh auth login --with-token
          git clone https://${{ secrets.gh_token }}@github.com/p3h3/DaronBMS-Interface-Web.git
          
          
          echo $(ls)
          cd https://github.com/p3h3/DaronBMS-Interface-Web
